<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPnzlKfy\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPnzlKfy/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPnzlKfy.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPnzlKfy\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPnzlKfy\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PnzlKfy',
    'container.build_id' => '0a8f57bb',
    'container.build_time' => 1563797628,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPnzlKfy');
