<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFzh61dg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFzh61dg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFzh61dg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFzh61dg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFzh61dg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Fzh61dg',
    'container.build_id' => '277ee099',
    'container.build_time' => 1563795128,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFzh61dg');
