<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDkZp3pQ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDkZp3pQ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDkZp3pQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDkZp3pQ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDkZp3pQ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DkZp3pQ',
    'container.build_id' => '53e89960',
    'container.build_time' => 1563786990,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDkZp3pQ');
